run:
  dir: outputs/hydra_logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

job:
  name: ${experiment.name}
  chdir: false

sweep:
  dir: outputs/hydra_sweeps/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

launcher:
  _target_: hydra._internal.BasicLauncher

sweeper:
  _target_: hydra._internal.BasicSweeper
  max_jobs: 1