# configs/hydra/job_logging/disabled.yaml  
# Disable Hydra's job logging for conservative tester compatibility
version: 1
formatters:
  simple:
    format: ''
handlers:
  null:
    class: logging.NullHandler
root:
  handlers: [null]
disable_existing_loggers: false